# Usign the Clean Blog theme

title: Séminaire Parisien des Mathématiques de l'Imagerie
author: imaging-in-paris
email: gabriel.peyre@ceremade.dauphine.fr
description: Séminaire Parisien des Mathématiques de l'Imagerie
baseurl: ""
url: "http://imaging-in-paris.github.io/"
github_username:  imaging-in-paris

# Build settings
markdown: redcarpet
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Imaging in Paris
gems:
  - jekyll-feed
  - jekyll-paginate
